services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: simulados
    volumes:
      - simulados:/var/lib/postgresql/data

volumes:
  simulados:
