import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Simulados SAP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <div className={`p-24 min-h-screen flex flex-col items-center`}>
          <nav className="flex justify-between self-start w-full">
            <Link href={"/"}>
              <span className="font-bold text-xl">Simulados</span>
            </Link>
            <nav className="font-normal">
              <ul>
                <li>
                  <Link href={"/upload-questions"}>
                    <span className="text-base">Enviar arquivo</span>
                  </Link>
                </li>
              </ul>
            </nav>

            {/* <Link href={"/"}>
              <span className="underline">Login</span>
            </Link> */}
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
