import "./globals.css";
import Body from "@/components/body";

export const metadata = {
  title: "Simulados",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <Body>{children}</Body>
    </html>
  );
}
